ui: tape
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: iphone
    version: latest
browserify:
  - transform:
      name: babelify
      compact: false
      stage: 0
