ui: tape
browsers:
  - name: chrome
    version: '44..latest'
  - name: firefox
    version: '40..latest'
  - name: iphone
    version: 'latest'
browserify:
  - transform:
      name: babelify
      compact: false
      stage: 0
